// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    ext.hilt_version ='2.38.1'
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:7.0.3"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.31"
        classpath "com.google.dagger:hilt-android-gradle-plugin:$hilt_version"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

ext {
    activity_version = "1.4.0"
    fragment_version = "1.4.1"
    hilt_version = "2.38.1"
    dagger_version = "2.40"
    retrofit_version = "2.9.0"
    lifecycle_extension_version = "2.2.0"
    kotlinx_version = "1.6.1"
    lifecycle_version = "2.3.1"
}